
name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:4.10-jdk8
    steps:
      - uses: actions/checkout@v4
      - run: gradle setupCIWorkspace build --no-daemon
      - uses: actions/upload-artifact@v4
        with: { name: mod, path: build/libs/*.jar }
